# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-21 23:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokensfcm',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
